import productImage from '@/assets/img/product.jpg'

export const discountData = [
    {
        id: 1,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 2,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 3,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 4,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 5,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 6,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 7,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
    {
        id: 8,
        image: productImage,
        title: 'مولتی ویتامین گوارش (مولتی مدیای بیماری‌های گوارشی + درسنامه تعاملی ویتامین)',
        salePrice: 138000,
        regularPrice: 198000,
        discountPercent: 30,
        isFavorite: false,
    },
]