// Shared Tailwind class map for the calculator tool pages (apps/tools).
// The .tool-* classes live in packages/tailwind-config/components.css.
// Each calculator folder has a toolStyles.ts that extends this map with
// its page-specific overrides, keeping the old `styles.xxx` keys working.
export const toolClasses: Record<string, string> = {
  container: "tool-container",
  tabBar: "tool-tab-bar",
  tab: "tool-tab",
  activeTab: "tool-tab-active",
  tabIndicator: "tool-tab-indicator",
  indicatorLeft: "tool-indicator-left",
  indicatorRight: "tool-indicator-right",
  sectionTitle: "tool-section-title",
  sectionContent: "tool-section-content",
  listItems: "",
  item: "tool-option",
  parameters: "tool-parameters",
  parameterRow: "tool-parameter-row",
  parameterText: "tool-parameter-text",
  separator: "tool-separator",
  switch: "tool-switch",
  slider: "tool-slider",
  calculateBar: "tool-calculate-bar",
  calculateButton: "tool-calculate-button",
  toast: "tool-toast",
  toastTitle: "tool-toast-title",
  toastText: "tool-toast-text",
  red: "tool-tone-red",
  yellow: "tool-tone-yellow",
  green: "tool-tone-green",
  gray: "tool-tone-gray",
  interpretation: "tool-interpretation",
  tableWrapper: "tool-table-wrapper",
  table: "tool-table",
  tableRow: "tool-table-row",
  inputGroup: "tool-input-group",
  inputLabel: "tool-input-label",
  input: "tool-input",
  formula: "tool-formula",
  scoreTableText: "[direction:ltr]",
  subText: "font-semibold",
  ltr: "[direction:ltr]",
};
