import drLearnImage from "@/assets/img/doctor-learn.png";
import { DiscountBadge } from "../../types/sidePanel";

export const discountData = [
  {
    id: 1,
    label: "دکترلرن",
    image: drLearnImage,
    title: "۲۰ هزار تومن تخفیف خرید دوره ها",
    expireDate: "۱ فروردین ۱۴۰۵",
    coinCount: 5,
    badge: [DiscountBadge.BRONZE],
    code: "6mKTe",
  },
  {
    id: 2,
    label: "دکترلرن",
    image: drLearnImage,
    title: "۲۰ هزار تومن تخفیف خرید دوره ها",
    expireDate: "۱ فروردین ۱۴۰۵",
    coinCount: 5,
    badge: [DiscountBadge.BRONZE, DiscountBadge.GREEN, DiscountBadge.SILVER],
    code: "6mKTe",
  },
  {
    id: 3,
    label: "دکترلرن",
    image: drLearnImage,
    title: "۲۰ هزار تومن تخفیف خرید دوره ها",
    expireDate: "۱ فروردین ۱۴۰۵",
    coinCount: 5,
    badge: [DiscountBadge.GREEN],
    code: "6mKTe",
  },
  {
    id: 4,
    label: "دکترلرن",
    image: drLearnImage,
    title: "۲۰ هزار تومن تخفیف خرید دوره ها",
    expireDate: "۱ فروردین ۱۴۰۵",
    coinCount: 10,
    badge: [DiscountBadge.SILVER],
    code: "6mKTe",
  },
  {
    id: 5,
    label: "دکترلرن",
    image: drLearnImage,
    title: "۲۰ هزار تومن تخفیف خرید دوره ها",
    expireDate: "۱ فروردین ۱۴۰۵",
    coinCount: 10,
    badge: [DiscountBadge.BRONZE, DiscountBadge.GREEN],
    code: "6mKTe",
  },
];
