import productImage from '@/assets/img/product.jpg';

export const learningData = [
  {
    id: 1,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
  {
    id: 2,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
  {
    id: 3,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
  {
    id: 4,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
  {
    id: 5,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
  {
    id: 6,
    title: 'دوره قلب اسکچی',
    image: productImage,
    cartId: 'DR67963',
    date: '۱۲ اردیبهشت ۱۴۰۲',
    price: 298000,
    language: 'FA',
    href: '#',
  },
];
