import { default as BackIcon } from "./icons/back";
import { default as BugIcon } from "./icons/bug";
import { default as CartIcon } from "./icons/cart";
import { default as ChatIcon } from "./icons/chat";
import { default as CoinIcon } from "./icons/coin";
import { default as ExitIcon } from "./icons/exit";
import { default as FriendsIcon } from "./icons/friends";
import { default as HeartIcon } from "./icons/heart";
import { default as HeartFillIcon } from "./icons/heartFill";
import { default as HomeIcon } from "./icons/home";
import { default as InfoIcon } from "./icons/info";
import { default as MessagesIcon } from "./icons/massages";
import { default as OrdersIcon } from "./icons/orders";
import { default as PlansIcon } from "./icons/plans";
import { default as ProfileIcon } from "./icons/profile";
import { default as QRScannerIcon } from "./icons/qrScanner";
import { default as ShareIcon } from "./icons/share";
import { default as StarIcon } from "./icons/star";
import { default as StarFillIcon } from "./icons/starFill";

export { BackIcon };
export { BugIcon };
export { CartIcon };
export { ChatIcon };
export { CoinIcon };
export { ExitIcon };
export { FriendsIcon };
export { HeartIcon };
export { HeartFillIcon };
export { HomeIcon };
export { InfoIcon };
export { MessagesIcon };
export { OrdersIcon };
export { PlansIcon };
export { ProfileIcon };
export { QRScannerIcon };
export { ShareIcon };
export { StarIcon };
export { StarFillIcon };
export { default as RecycleBin } from "./icons/recycleBin";
