import { default as BackIcon } from "./svg/back";
import { default as BugIcon } from "./svg/bug";
import { default as CartIcon } from "./svg/cart";
import { default as ChatIcon } from "./svg/chat";
import { default as CoinIcon } from "./svg/coin";
import { default as ExitIcon } from "./svg/exit";
import { default as FriendsIcon } from "./svg/friends";
import { default as HeartIcon } from "./svg/heart";
import { default as HeartFillIcon } from "./svg/heartFill";
import { default as HomeIcon } from "./svg/home";
import { default as InfoIcon } from "./svg/info";
import { default as MessagesIcon } from "./svg/massages";
import { default as OrdersIcon } from "./svg/orders";
import { default as PlansIcon } from "./svg/plans";
import { default as ProfileIcon } from "./svg/profile";
import { default as QrScannerIcon } from "./svg/qrScanner";
import { default as ShareIcon } from "./svg/share";
import { default as StarIcon } from "./svg/star";
import { default as StarFillIcon } from "./svg/starFill";

export { BackIcon };
export { BugIcon };
export { CartIcon };
export { ChatIcon };
export { CoinIcon };
export { ExitIcon };
export { FriendsIcon };
export { HeartIcon };
export { HeartFillIcon };
export { HomeIcon };
export { InfoIcon };
export { MessagesIcon };
export { OrdersIcon };
export { PlansIcon };
export { ProfileIcon };
export { QrScannerIcon };
export { ShareIcon };
export { StarIcon };
export { StarFillIcon };
export { default as RecycleBin } from "./svg/recycleBin";
export { default as Squircle } from "./svg/squircle";
export { default as AngleDown } from "./svg/angleDown";
export { default as Close_X } from "./svg/close_x";
